import { useCallback, useEffect, useRef, useState } from 'react'
import { useInfiniteQuery, useQuery, useQueryClient } from '@tanstack/react-query'
import { useVirtualizer } from '@tanstack/react-virtual'
import { Activity, ArrowDown, ArrowUpRight, Check, ChevronDown, Command, Folder, Grid2X2, Heart, Images, Layers3, List, LogOut, Menu, Plus, Search, Settings2, SlidersHorizontal, Sparkles, Tag, Trash2, Upload, WandSparkles, X } from 'lucide-react'
import { api, post, setCSRF, type AST, type Asset, type Collection, type Job, type Library, type SearchInput, type SearchResult, type Session } from './api'
import { Button } from './components/ui/button'
import { Modal } from './components/ui/dialog'
import { SearchBuilder, emptyCondition } from './components/SearchBuilder'
import { ExportDialog } from './components/Downloads'
import { AssetViewer } from './components/AssetViewer'
import { ImportView, JobsView, RulesView, SettingsView } from './components/Management'
import { sizeLabel } from './lib/utils'

function Login({ login }: { login: (session: Session) => void }) {
  const [username, setUsername] = useState('admin'), [password, setPassword] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  return <div className="login-page"><div className="login-art"><div className="login-orbit orbit-one" /><div className="login-orbit orbit-two" /><div className="brand"><div className="brand-mark"><Layers3 size={25} /></div><span>GenMedia <strong>Vault</strong></span></div><div className="login-message"><p className="eyebrow">A HOME FOR EVERY CREATION</p><h1>灵感有迹可循。</h1><p>收藏每一次生成。<br />找回每一个参数。<br />让创作，接着发生。</p><span className="login-footer">本地优先 · 元信息驱动 · 你的创作档案</span></div></div><main className="login-form"><div><span className="badge"><span className="online-dot" />私有工作空间</span><h2>欢迎回到你的资产库</h2><p className="muted">登录后，继续整理与探索你的创作。</p><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { login(await post<Session>('/auth/login', { username, password })) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }} className="form-stack"><label>用户名<input autoComplete="username" required value={username} onChange={e => setUsername(e.target.value)} /></label><label>密码<input autoComplete="current-password" type="password" required value={password} onChange={e => setPassword(e.target.value)} /></label>{error && <div role="alert" className="error-box">{error}</div>}<Button disabled={busy} type="submit">{busy ? '正在登录…' : '进入工作空间'}<ArrowUpRight size={17} /></Button></form><p className="login-hint">账号由管理员创建。首次部署请使用配置中的管理员密码。</p></div></main></div>
}

function Gallery({ assets, selected, select, open, list, loadMore, hasMore, fetching }: { assets: Asset[]; selected: Set<string>; select: (id: string, shift: boolean) => void; open: (id: string) => void; list: boolean; loadMore: () => void; hasMore: boolean; fetching: boolean }) {
  const parent = useRef<HTMLDivElement>(null)
  const [width, setWidth] = useState(1000)
  useEffect(() => { if (!parent.current) return; const observer = new ResizeObserver(entries => setWidth(entries[0].contentRect.width)); observer.observe(parent.current); return () => observer.disconnect() }, [])
  const columns = list ? 1 : Math.max(1, Math.floor(width / 245)), rowHeight = list ? 88 : 310
  const rows = Math.ceil(assets.length / columns)
  const virtual = useVirtualizer({ count: rows, getScrollElement: () => parent.current, estimateSize: () => rowHeight, overscan: 3 })
  const visible = virtual.getVirtualItems()
  useEffect(() => { if (hasMore && !fetching && visible.at(-1) && visible.at(-1)!.index >= rows - 3) loadMore() }, [visible, hasMore, fetching, rows, loadMore])
  return <div className="gallery-scroll" ref={parent}><div className="gallery-virtual" style={{ height: virtual.getTotalSize() }}>{visible.map(row => <div className={list ? 'asset-row' : 'asset-grid-row'} key={row.key} style={{ position: 'absolute', top: row.start, left: 0, width: '100%', height: rowHeight, gridTemplateColumns: `repeat(${columns}, minmax(0, 1fr))` }}>
    {assets.slice(row.index * columns, (row.index + 1) * columns).map(asset => <article className={`asset-card ${list ? 'asset-card-list' : ''} ${selected.has(asset.id) ? 'selected' : ''}`} key={asset.id}><div className="asset-picture"><button className="image-open" aria-label={`查看 ${asset.filename}`} onClick={() => open(asset.id)}><img loading="lazy" src={asset.thumbnail} alt={asset.filename} onError={e => { e.currentTarget.style.opacity = '0'; e.currentTarget.parentElement?.classList.add('image-unavailable') }} /></button><button className={`selection-check ${selected.has(asset.id) ? 'checked' : ''}`} aria-label={`选择 ${asset.filename}`} aria-pressed={selected.has(asset.id)} onClick={e => select(asset.id, e.shiftKey)}>{selected.has(asset.id) && <Check size={14} />}</button>{asset.favorite && <span className="asset-heart"><Heart size={14} fill="currentColor" /></span>}<span className="asset-generator">{asset.generator === 'unknown' ? 'IMAGE' : asset.generator.toUpperCase()}</span></div><button className="asset-caption" onClick={() => open(asset.id)}><strong title={asset.filename}>{asset.filename}</strong><span>{asset.model || '未识别模型'}</span><div><small>{asset.width} × {asset.height}</small><small>{asset.rating ? '★'.repeat(asset.rating) : sizeLabel(asset.file_size)}</small></div></button></article>)}
  </div>)}</div>{hasMore && <div className="gallery-more"><Button variant="ghost" disabled={fetching} onClick={loadMore}><ArrowDown size={14} />{fetching ? '正在加载…' : '加载更多'}</Button></div>}</div>
}

export default function App() {
  const client = useQueryClient()
  const sessionQuery = useQuery({ queryKey: ['session'], queryFn: async () => { const active = await api<Session>('/auth/me'); setCSRF(active.csrf); return active }, retry: false, staleTime: Infinity })
  const session = sessionQuery.data
  const params = new URLSearchParams(window.location.search)
  const [view, setView] = useState(params.get('view') || 'library'), [query, setQuery] = useState(params.get('q') || ''), [draft, setDraft] = useState(query)
  const [libraryId, setLibraryId] = useState(params.get('library') || ''), [collectionId, setCollectionId] = useState(params.get('collection') || '')
  const [sort, setSort] = useState<SearchInput['sort']>('imported_desc'), [list, setList] = useState(false), [selected, setSelected] = useState(new Set<string>()), [viewer, setViewer] = useState<string | null>(params.get('asset'))
  const [toast, setToast] = useState<{ message: string; error: boolean } | null>(null), [builder, setBuilder] = useState<AST | null>(null), [builderError, setBuilderError] = useState('')
  const [collectionForm, setCollectionForm] = useState<Collection | null>(null), [mobileNav, setMobileNav] = useState(false), [tagValue, setTagValue] = useState(''), [tagFilter, setTagFilter] = useState('')
  const [exportOpen, setExportOpen] = useState(false)
  const lastSelected = useRef<string | null>(null)
  const jobRevision = useRef('')
  const logged = !!session
  const isAdmin = session?.user.role === 'admin'
  const libraryQuery = useQuery({ queryKey: ['libraries'], queryFn: () => api<Library[]>('/libraries'), enabled: logged })
  const collectionQuery = useQuery({ queryKey: ['collections'], queryFn: () => api<Collection[]>('/collections'), enabled: logged })
  const jobsQuery = useQuery({ queryKey: ['jobs'], queryFn: () => api<Job[]>('/jobs'), enabled: logged, refetchInterval: 5000 })
  const tagsQuery = useQuery({ queryKey: ['tags'], queryFn: () => api<{ id: string; name: string; namespace: string; count: number }[]>('/tags'), enabled: logged && view === 'tags' })
  const libraries = libraryQuery.data || [], collections = collectionQuery.data || [], jobs = jobsQuery.data || []
  useEffect(() => {
    const revision = (jobsQuery.data || []).map(job => `${job.id}:${job.status}`).join('|')
    if (revision !== jobRevision.current) {
      if (jobRevision.current) {
        void client.invalidateQueries({ queryKey: ['assets'] })
        void client.invalidateQueries({ queryKey: ['libraries'] })
        void client.invalidateQueries({ queryKey: ['tags'] })
      }
      jobRevision.current = revision
    }
  }, [jobsQuery.data, client])
  const gallery = ['library', 'trash'].includes(view)
  const results = useInfiniteQuery({ queryKey: ['assets', query, libraryId, collectionId, sort, view, session?.user.id], enabled: logged && gallery, initialPageParam: undefined as string | undefined,
    queryFn: ({ pageParam }) => post<SearchResult>('/search', { query, library_id: libraryId || null, collection_id: collectionId || null, sort, trash: view === 'trash', cursor: pageParam, limit: 60, facets: !pageParam }), getNextPageParam: page => page.next_cursor || undefined })
  const assets = results.data?.pages.flatMap(p => p.items) || []
  const facets = results.data?.pages[0]?.facets as { total?: number; generators?: Record<string, number> } | undefined
  const total = facets?.total || 0
  useEffect(() => { if (session) setCSRF(session.csrf) }, [session])
  useEffect(() => { const expired = () => { client.removeQueries({ predicate: q => q.queryKey[0] !== 'session' }); client.setQueryData(['session'], null) }; window.addEventListener('session-expired', expired); return () => window.removeEventListener('session-expired', expired) }, [client])
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(null), toast.error ? 9000 : 3500); return () => clearTimeout(timer) } }, [toast])
  useEffect(() => { setSelected(new Set()); lastSelected.current = null }, [query, libraryId, collectionId, view])
  useEffect(() => { const pop = () => { const p = new URLSearchParams(location.search); setView(p.get('view') || 'library'); setQuery(p.get('q') || ''); setDraft(p.get('q') || ''); setLibraryId(p.get('library') || ''); setCollectionId(p.get('collection') || ''); setViewer(p.get('asset')) }; window.addEventListener('popstate', pop); return () => window.removeEventListener('popstate', pop) }, [])
  const go = (next: { view?: string; query?: string; library?: string; collection?: string; asset?: string | null }) => {
    const v = next.view ?? view, q = next.query ?? query, l = next.library ?? libraryId, c = next.collection ?? collectionId
    setView(v); setQuery(q); setDraft(q); setLibraryId(l); setCollectionId(c); setMobileNav(false)
    const p = new URLSearchParams(); if (v !== 'library') p.set('view', v); if (q) p.set('q', q); if (l) p.set('library', l); if (c) p.set('collection', c)
    if (next.asset !== undefined) { setViewer(next.asset); if (next.asset) p.set('asset', next.asset) }
    history.pushState(null, '', p.size ? `?${p}` : location.pathname)
  }
  const search = (q: string) => go({ view: 'library', query: q, collection: '' })
  const run = async (task: () => Promise<unknown>, message?: string) => { try { await task(); await client.invalidateQueries({ predicate: q => q.queryKey[0] !== 'session' }); if (message) setToast({ message, error: false }) } catch (e) { setToast({ message: (e as Error).message, error: true }) } }
  const bulk = (action: string, value?: string | number | boolean | null) => run(() => post('/assets/bulk', { asset_ids: Array.from(selected), action, value }), action === 'export' ? '导出任务已创建，请到任务页下载' : '操作已保存')
  const select = (id: string, shift: boolean) => { const next = new Set(selected); if (shift && lastSelected.current) { const from = assets.findIndex(a => a.id === lastSelected.current), to = assets.findIndex(a => a.id === id); for (const a of assets.slice(Math.min(from, to), Math.max(from, to) + 1)) next.add(a.id) } else if (next.has(id)) next.delete(id); else next.add(id); lastSelected.current = id; setSelected(next) }
  const loadMore = useCallback(() => { void results.fetchNextPage() }, [results.fetchNextPage])
  const openBuilder = async () => { try { const parsed = await post<{ ast: AST }>('/search/parse', { query: draft }); setBuilder(parsed.ast.root.type === 'and' || parsed.ast.root.type === 'or' ? parsed.ast : { version: 1, root: { type: 'and', children: [parsed.ast.root] } }); setBuilderError('') } catch (e) { setBuilderError((e as Error).message); setBuilder({ version: 1, root: { type: 'and', children: [emptyCondition()] } }) } }
  const saveCollection = () => run(async () => { if (!collectionForm) return; const { id, ast: _ast, ...body } = collectionForm; await api(id ? `/collections/${id}` : '/collections', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(body) }); setCollectionForm(null) }, '集合已保存')
  if (sessionQuery.isPending) return <div className="app-loading"><Layers3 size={34} /><p>正在打开资产库…</p></div>
  if (!session) return <Login login={s => { client.removeQueries({ predicate: q => q.queryKey[0] !== 'session' }); setCSRF(s.csrf); client.setQueryData(['session'], s) }} />
  const title = view === 'trash' ? '回收站' : libraryId ? libraries.find(l => l.id === libraryId)?.name || '媒体库' : collectionId ? collections.find(c => c.id === collectionId)?.name || '集合' : '全部资产'
  const busyJobs = jobs.filter(j => ['pending', 'running'].includes(j.status)).length
  return <div className="app-shell"><aside className={`sidebar ${mobileNav ? 'sidebar-open' : ''}`}><a href="/" className="brand" onClick={e => { e.preventDefault(); go({ view: 'library', query: '', library: '', collection: '' }) }}><div className="brand-mark"><Layers3 size={23} /></div><span>GenMedia <strong>Vault</strong></span></a><div className="workspace"><span className="workspace-icon">G</span><div><strong>创作档案</strong><small><span className="online-dot" />共享工作空间</small></div><ChevronDown size={15} /></div>
    <p className="nav-label">工作空间</p><nav>{[{ key: 'library', icon: Images, label: '全部资产', count: libraries.reduce((n, l) => n + l.count, 0) }, { key: 'favorite', icon: Heart, label: '我的收藏' }, { key: 'tags', icon: Tag, label: '标签探索' }, { key: 'import', icon: Upload, label: '导入文件' }, { key: 'jobs', icon: Activity, label: '后台任务', count: busyJobs }].map(item => <button className={`nav-item ${item.key === view && !libraryId && !collectionId && query !== 'favorite:true' || item.key === 'favorite' && query === 'favorite:true' ? 'active' : ''}`} key={item.key} onClick={() => go({ view: item.key === 'favorite' ? 'library' : item.key, query: item.key === 'favorite' ? 'favorite:true' : '', library: '', collection: '' })}><item.icon size={17} /><span>{item.label}</span>{item.count != null && <small>{item.count.toLocaleString()}</small>}</button>)}</nav>
    <div className="nav-label row between">媒体库{isAdmin && <button aria-label="添加媒体库" className="icon-button" onClick={() => go({ view: 'settings' })}><Plus size={14} /></button>}</div><nav>{libraries.map(library => <button key={library.id} className={`nav-item ${gallery && libraryId === library.id ? 'active' : ''}`} onClick={() => go({ view: 'library', query: '', library: library.id, collection: '' })}><Folder size={16} /><span>{library.name}</span><small>{library.count.toLocaleString()}</small></button>)}</nav>
    <div className="nav-label row between">集合<button aria-label="创建集合" className="icon-button" onClick={() => setCollectionForm({ id: '', name: '', kind: 'static', query: '', ast: null, revision: 1 })}><Plus size={14} /></button></div><nav>{collections.map(collection => <div className="collection-nav" key={collection.id}><button className={`nav-item ${collectionId === collection.id && gallery ? 'active' : ''}`} onClick={() => go({ view: 'library', query: '', library: '', collection: collection.id })}>{collection.kind === 'smart' ? <Sparkles size={16} /> : <Folder size={16} />}<span>{collection.name}</span></button><button className="collection-edit icon-button" aria-label={`编辑 ${collection.name}`} onClick={() => setCollectionForm({ ...collection })}><Settings2 size={13} /></button></div>)}</nav>
    <div className="sidebar-bottom">{isAdmin && <button className={`nav-item ${view === 'rules' ? 'active' : ''}`} onClick={() => go({ view: 'rules' })}><WandSparkles size={17} /><span>自动分类</span></button>}<button className={`nav-item ${view === 'trash' ? 'active' : ''}`} onClick={() => go({ view: 'trash', query: '', library: '', collection: '' })}><Trash2 size={17} /><span>回收站</span></button><button className={`nav-item ${view === 'settings' ? 'active' : ''}`} onClick={() => go({ view: 'settings' })}><Settings2 size={17} /><span>设置</span></button><div className="profile"><div className="avatar">{session.user.username[0].toUpperCase()}</div><div><strong>{session.user.username}</strong><small>{isAdmin ? '管理员' : '普通成员'}</small></div><button className="icon-button" aria-label="退出登录" onClick={() => run(async () => { await post('/auth/logout'); client.removeQueries({ predicate: q => q.queryKey[0] !== 'session' }); client.setQueryData(['session'], null) })}><LogOut size={16} /></button></div></div></aside>
    {mobileNav && <button className="nav-scrim" aria-label="关闭导航" onClick={() => setMobileNav(false)} />}
    <main className="main-content"><header className="topbar"><button className="icon-button mobile-menu" aria-label="打开导航" onClick={() => setMobileNav(true)}><Menu size={20} /></button><form className="search-bar" onSubmit={e => { e.preventDefault(); search(draft) }}><Search size={18} /><input aria-label="搜索资产" placeholder='搜索提示词、模型、标签… 或输入 model:pony AND rating:>=4' value={draft} onChange={e => setDraft(e.target.value)} /><kbd>↵</kbd><button type="button" className="filter-toggle" onClick={openBuilder} aria-label="高级筛选"><SlidersHorizontal size={16} /><span>高级筛选</span></button></form><Button size="sm" onClick={() => go({ view: 'import' })}><Plus size={16} /><span>导入</span></Button></header>
      {gallery ? <><section className="gallery-header"><div><div className="eyebrow">YOUR GENERATIVE ARCHIVE</div><h1>{title}<span>{total.toLocaleString()}</span></h1><p>{view === 'trash' ? '删除的资产保留在这里，可由管理员恢复。索引库源文件保持原样。' : '每一次生成，都值得被找到。'}</p></div><div className="header-emblem"><Layers3 size={46} strokeWidth={0.8} /></div></section>
        <div className="gallery-toolbar"><div className="row"><Button variant={selected.size ? 'default' : 'outline'} size="sm" onClick={() => setSelected(selected.size ? new Set() : new Set(assets.map(a => a.id)))}><Check size={14} />{selected.size ? `已选 ${selected.size}` : '选择当前结果'}</Button>{query && <span className="query-chip"><code>{query}</code><button aria-label="清除搜索" onClick={() => search('')}><X size={13} /></button></span>}</div><div className="row"><button className="text-button save-search" onClick={() => setCollectionForm({ id: '', name: '', kind: 'smart', query, ast: null, revision: 1 })}><Sparkles size={14} />保存搜索</button><select aria-label="排序方式" value={sort} onChange={e => setSort(e.target.value as SearchInput['sort'])}><option value="imported_desc">最近导入</option><option value="imported_asc">最早导入</option><option value="created_desc">文件日期</option><option value="rating_desc">我的评分</option><option value="size_desc">文件大小</option><option value="resolution_desc">分辨率</option><option value="filename_asc">文件名</option></select><div className="view-switch"><button aria-label="网格视图" className={!list ? 'active' : ''} onClick={() => setList(false)}><Grid2X2 size={16} /></button><button aria-label="列表视图" className={list ? 'active' : ''} onClick={() => setList(true)}><List size={16} /></button></div></div></div>
        {!!facets?.generators && Object.keys(facets.generators).length > 1 && <div className="facets"><span>生成器</span>{Object.entries(facets.generators).map(([generator, count]) => <button className="tag" key={generator} onClick={() => search(`${query ? `(${query}) AND ` : ''}generator:${JSON.stringify(generator)}`)}>{generator}<small>{count.toLocaleString()}</small></button>)}</div>}
        {results.error ? <div role="alert" className="error-box gallery-error">{results.error.message}</div> : results.isPending ? <div className="gallery-skeleton">{Array.from({ length: 8 }, (_, i) => <div key={i} />)}</div> : !assets.length ? <div className="empty-state"><div className="empty-icon"><Images size={36} strokeWidth={1.2} /></div><h2>{query ? '还没有匹配的创作' : view === 'trash' ? '回收站是空的' : '为你的下一次灵感，建一座档案库'}</h2><p>{query ? '试试减少筛选条件，或检查元信息中的模型名称。' : '从 NovelAI、Stable Diffusion 或 ComfyUI 导入图片，找回它们背后的生成参数。'}</p><Button onClick={() => query ? search('') : go({ view: 'import' })}>{query ? '清除搜索条件' : '导入第一批图片'}<ArrowUpRight size={16} /></Button><div className="empty-features"><span><Command size={16} />复杂条件搜索</span><span><WandSparkles size={16} />元信息自动分类</span><span><Layers3 size={16} />原件完整保留</span></div></div> : <Gallery assets={assets} selected={selected} select={select} open={id => go({ asset: id })} list={list} loadMore={loadMore} hasMore={results.hasNextPage} fetching={results.isFetchingNextPage} />}
        {!!selected.size && <div className="bulk-bar"><strong>{selected.size} 张已选</strong><input aria-label="批量标签" placeholder="添加标签…" value={tagValue} onChange={e => setTagValue(e.target.value)} /><Button variant="ghost" size="sm" disabled={!tagValue} onClick={() => bulk('add_tag', tagValue)}>添加</Button><Button variant="ghost" size="sm" disabled={!tagValue} onClick={() => bulk('remove_tag', tagValue)}>移除人工标签</Button><select aria-label="添加到集合" value="" onChange={e => { if (e.target.value) void bulk('collection_add', e.target.value) }}><option value="">加入集合</option>{collections.filter(c => c.kind === 'static').map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select><select aria-label="批量评分" value="" onChange={e => { if (e.target.value) void bulk('rating', Number(e.target.value)) }}><option value="">评分</option>{[1, 2, 3, 4, 5].map(n => <option key={n} value={n}>{n} ★</option>)}</select><Button variant="ghost" size="icon" aria-label="批量收藏" onClick={() => bulk('favorite', true)}><Heart size={16} /></Button><Button variant="outline" size="sm" onClick={() => setExportOpen(true)}>批量下载 ZIP</Button>{isAdmin && <><Button variant="ghost" size="sm" onClick={() => bulk('reparse')}>重新解析</Button><Button variant="destructive" size="sm" onClick={() => bulk(view === 'trash' ? 'restore' : 'trash')}>{view === 'trash' ? '恢复' : '回收站'}</Button></>}<button className="icon-button" aria-label="取消选择" onClick={() => setSelected(new Set())}><X size={17} /></button></div>}
      </> : <div className="page-scroll">{view === 'import' && <ImportView libraries={libraries} admin={isAdmin} run={run} />}{view === 'jobs' && <JobsView jobs={jobs} admin={isAdmin} userId={session.user.id} run={run} />}{view === 'rules' && isAdmin && <RulesView run={run} collections={collections} />}{view === 'settings' && <SettingsView run={run} libraries={libraries} admin={isAdmin} />}{view === 'tags' && <div className="content-narrow"><div className="section-intro"><p className="eyebrow">EXPLORE BY METADATA</p><h2>从标签，发现关联</h2><p>生成参数、自动规则与人工整理，汇成你的创作地图。</p></div><input aria-label="筛选标签" placeholder="筛选标签或命名空间…" value={tagFilter} onChange={e => setTagFilter(e.target.value)} /><div className="tag-explorer">{tagsQuery.data?.filter(t => t.name.includes(tagFilter)).map(tag => <div className="panel tag-explorer-card" key={tag.id}><button className="tag-explorer-search" onClick={() => search(`tag:${JSON.stringify(tag.name)}`)}><span className="eyebrow">{tag.namespace || '通用'}</span><strong>{tag.name}</strong><span className="muted">{tag.count} 张图片 <ArrowUpRight size={14} /></span></button>{isAdmin && <Button variant="ghost" size="sm" aria-label={`删除共享标签 ${tag.name}`} onClick={() => { if (window.confirm(`删除共享标签「${tag.name}」？将从 ${tag.count} 张图片移除，自动分类也不会重新添加。原图不受影响。手工再次添加可重新启用。`)) void run(() => api(`/tags/${tag.id}`, { method: 'DELETE' }), '共享标签已删除') }}><Trash2 size={13} />删除</Button>}</div>)}</div>{!tagsQuery.data?.length && <div className="empty-state"><Tag size={30} /><p>导入图片后，标签会出现在这里。</p></div>}</div>}</div>}
      <footer className="statusbar"><span><span className="online-dot" />GenMedia Vault <small>v0.2</small></span><span>原件保留 · 元信息可追溯{busyJobs > 0 && ` · ${busyJobs} 个任务处理中`}</span></footer>
    </main>
    {exportOpen && <ExportDialog ids={Array.from(selected)} open close={() => setExportOpen(false)} run={run} />}
    <AssetViewer id={viewer} assets={assets} admin={isAdmin} close={() => go({ asset: null })} navigate={id => go({ asset: id })} run={run} search={search} />
    <Modal open={!!builder} onOpenChange={open => !open && setBuilder(null)} title="高级筛选" description="组合全部、任一和排除条件。应用后会同步为可分享的搜索表达式。">{builder && <><SearchBuilder value={builder} onChange={setBuilder} />{builderError && <div role="alert" className="error-box">{builderError}</div>}<div className="modal-footer"><Button variant="ghost" onClick={() => setBuilder({ version: 1, root: { type: 'and', children: [] } })}>清空条件</Button><Button onClick={async () => { try { const result = await post<{ query: string }>('/search/parse', { ast: builder }); search(result.query); setBuilder(null) } catch (e) { setBuilderError((e as Error).message) } }}>应用筛选</Button></div></>}</Modal>
    <Modal open={!!collectionForm} onOpenChange={open => !open && setCollectionForm(null)} title={collectionForm?.id ? '编辑集合' : '创建集合'} description="普通集合手动整理；智能集合随搜索条件自动更新。">{collectionForm && <form className="form-stack" onSubmit={e => { e.preventDefault(); void saveCollection() }}><label>集合名称<input required value={collectionForm.name} onChange={e => setCollectionForm({ ...collectionForm, name: e.target.value })} /></label><label>集合类型<select disabled={!!collectionForm.id} value={collectionForm.kind} onChange={e => setCollectionForm({ ...collectionForm, kind: e.target.value as 'static' | 'smart' })}><option value="static">普通集合</option><option value="smart">智能集合</option></select></label>{collectionForm.kind === 'smart' && <label>搜索条件<textarea rows={4} value={collectionForm.query} onChange={e => setCollectionForm({ ...collectionForm, query: e.target.value })} placeholder='model:pony AND rating:>=4' /></label>}<div className="row between">{collectionForm.id && <Button type="button" variant="destructive" onClick={() => run(async () => { await api(`/collections/${collectionForm.id}`, { method: 'DELETE' }); setCollectionForm(null); go({ collection: '' }) }, '集合已删除，原图保留')}>删除集合</Button>}<Button type="submit">保存集合</Button></div></form>}</Modal>
    {toast && <div role={toast.error ? 'alert' : 'status'} className={`toast ${toast.error ? 'toast-error' : ''}`}>{toast.error ? <X size={17} /> : <Check size={17} />}<span>{toast.message}</span><button aria-label="关闭提示" onClick={() => setToast(null)}><X size={14} /></button></div>}
  </div>
}

