import { test, expect } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'

const password = process.env.GMV_E2E_PASSWORD || JSON.parse(fs.readFileSync(path.resolve('../data/test-environment.json'), 'utf8')).admin_password
test('upload → metadata → search → personal rating → export → logout', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('用户名', { exact: true }).fill('admin')
  await page.getByLabel('密码', { exact: true }).fill(password)
  await page.getByRole('button', { name: '进入工作空间' }).click()
  await expect(page.getByRole('heading', { name: /全部资产/ })).toBeVisible()
  await page.screenshot({ path: '../test-artifacts/gallery-empty.png', fullPage: true })
  await page.getByRole('button', { name: '导入文件', exact: true }).click()
  await page.getByLabel('选择上传文件', { exact: true }).setInputFiles(path.resolve('../backend/tests/fixtures/a1111.png'))
  await page.getByRole('button', { name: '提交导入' }).click()
  await expect(page.getByRole('status')).toContainText('导入任务已提交')
  await page.getByRole('button', { name: /全部资产/ }).click()
  await page.getByLabel('搜索资产', { exact: true }).fill('seed:18446744073709551615')
  await page.getByLabel('搜索资产', { exact: true }).press('Enter')
  await expect.poll(async () => {
    await page.reload()
    await page.getByRole('button', { name: '查看 a1111.png', exact: true }).waitFor({ state: 'visible', timeout: 3000 }).catch(() => {})
    return page.getByRole('button', { name: '查看 a1111.png', exact: true }).count()
  }, { timeout: 20000 }).toBe(1)
  await page.screenshot({ path: '../test-artifacts/gallery.png', fullPage: true })
  await page.getByRole('button', { name: '查看 a1111.png', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('button', { name: '18446744073709551615', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '评分 5', exact: true }).focus()
  await page.keyboard.press('5')
  await page.getByLabel('私人备注', { exact: true }).fill(`端到端测试：保留这个配色 ${Date.now()}`)
  await page.getByRole('button', { name: '保存备注', exact: true }).click()
  await page.screenshot({ path: '../test-artifacts/detail.png', fullPage: true })
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByLabel('搜索资产', { exact: true }).fill('rating:>=5 AND prompt.tag:"white hair"')
  await page.getByLabel('搜索资产', { exact: true }).press('Enter')
  await expect(page.getByRole('button', { name: '查看 a1111.png', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '高级筛选', exact: true }).click()
  await expect(page.getByLabel('搜索字段').first()).toHaveValue('rating')
  await page.getByRole('button', { name: '应用筛选', exact: true }).click()
  await expect(page.getByRole('button', { name: '查看 a1111.png', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '选择 a1111.png', exact: true }).click()
  const exportResponse = page.waitForResponse(response => response.url().endsWith('/api/v1/assets/bulk') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '导出', exact: true }).click()
  const exportJob = (await (await exportResponse).json()).job_id
  await page.getByRole('button', { name: /后台任务/ }).click()
  await expect(page.locator(`a[href="/api/v1/jobs/${exportJob}/download"]`)).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: '退出登录', exact: true }).click()
  await expect(page.getByRole('button', { name: '进入工作空间', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('mobile navigation remains usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByLabel('用户名', { exact: true }).fill('admin')
  await page.getByLabel('密码', { exact: true }).fill(password)
  await page.getByRole('button', { name: '进入工作空间' }).click()
  await page.getByRole('button', { name: '打开导航', exact: true }).click()
  await page.getByRole('button', { name: '导入文件', exact: true }).click()
  await expect(page.getByRole('heading', { name: '把灵感留在这里', exact: true })).toBeVisible()
  await expect.poll(() => page.locator('.sidebar').evaluate(element => element.getBoundingClientRect().right)).toBeLessThanOrEqual(0)
  await page.screenshot({ path: '../test-artifacts/mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
})
