import { test, expect } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'

const password = process.env.GMV_E2E_PASSWORD || JSON.parse(fs.readFileSync(path.resolve('../data/test-environment.json'), 'utf8')).admin_password
test('NovelAI roles → shared colored groups → reference image → ZIP → admin backup → delete shared tag', async ({ page, context }) => {
  test.setTimeout(90000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/')
  await page.getByLabel('用户名', { exact: true }).fill('admin')
  await page.getByLabel('密码', { exact: true }).fill(password)
  await page.getByRole('button', { name: '进入工作空间' }).click()
  await page.getByRole('button', { name: '导入文件', exact: true }).click()
  await page.getByLabel('选择上传文件', { exact: true }).setInputFiles(path.resolve('../backend/tests/fixtures/novelai-characters.png'))
  await page.getByRole('button', { name: '提交导入' }).click()
  await expect(page.getByRole('status')).toContainText('导入任务已提交')
  await page.getByRole('button', { name: /全部资产/ }).click()
  await expect(page.getByRole('button', { name: '查看 novelai-characters.png', exact: true })).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: '查看 novelai-characters.png', exact: true }).click()
  await expect(page.getByRole('heading', { name: '角色 1', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '角色 2', exact: true })).toBeVisible()
  await expect(page.getByText('white hair, blue eyes', { exact: true })).toBeVisible()
  await page.screenshot({ path: '../test-artifacts/v02-characters.png', fullPage: true })
  await page.getByRole('button', { name: '标签', exact: true }).click()
  const sharedTag = `测试标签:${Date.now()}`
  await page.getByLabel('新标签', { exact: true }).fill(sharedTag)
  await page.getByRole('button', { name: '添加标签', exact: true }).click()
  await page.getByLabel('提示词来源', { exact: true }).selectOption('character:0:positive')
  await page.locator('.token-picker').getByRole('button', { name: 'white hair', exact: true }).click()
  await page.locator('.token-picker').getByRole('button', { name: 'blue eyes', exact: true }).click()
  await page.getByRole('button', { name: /新建分组/ }).click()
  await page.getByLabel('分组名称', { exact: true }).last().fill('角色外观')
  await page.getByLabel('分组颜色 角色外观', { exact: true }).last().fill('#b48ead')
  await page.getByRole('button', { name: '保存分组', exact: true }).click()
  await expect(page.getByText('共享 · 已保存', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '保存分组', exact: true })).toBeDisabled()
  await page.getByLabel('复制组 角色外观', { exact: true }).last().check()
  await page.getByRole('button', { name: '复制选中分组', exact: true }).click()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe('white hair, blue eyes')
  await page.screenshot({ path: '../test-artifacts/v02-groups.png', fullPage: true })
  await page.getByRole('button', { name: '参考图', exact: true }).click()
  await page.getByLabel('参考图说明', { exact: true }).fill('双人站姿')
  await page.getByLabel('参考图关联角色', { exact: true }).selectOption('0')
  const referenceCount = await page.locator('.reference-card').count()
  await page.getByLabel('添加参考图', { exact: true }).setInputFiles(path.resolve('../backend/tests/fixtures/plain.webp'))
  await expect(page.locator('.reference-card')).toHaveCount(referenceCount + 1)
  await expect(page.locator('.reference-card img').last()).toBeVisible()
  await page.screenshot({ path: '../test-artifacts/v02-references.png', fullPage: true })
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '选择 novelai-characters.png', exact: true }).click()
  await page.getByRole('button', { name: '批量下载 ZIP', exact: true }).click()
  await page.getByLabel('同时包含生成参数、提示词分组和我的备注').check()
  const exportDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: '打包并下载 ZIP', exact: true }).click()
  await (await exportDownload).saveAs('../test-artifacts/v02-export.zip')
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByLabel('备份备注', { exact: true }).fill('v0.2 浏览器验证')
  const backupDownload = page.waitForEvent('download', { timeout: 40000 })
  await page.getByRole('button', { name: '创建备份并下载', exact: true }).click()
  await (await backupDownload).saveAs('../test-artifacts/v02-backup.zip')
  await page.screenshot({ path: '../test-artifacts/v02-backup.png', fullPage: true })
  await page.getByRole('button', { name: '标签探索', exact: true }).click()
  await page.getByLabel('筛选标签', { exact: true }).fill(sharedTag)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: `删除共享标签 ${sharedTag}`, exact: true }).click()
  await expect(page.getByRole('button', { name: `删除共享标签 ${sharedTag}`, exact: true })).toHaveCount(0)
  expect(errors).toEqual([])
})
