import { test, expect } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'

const password = process.env.GMV_E2E_PASSWORD || JSON.parse(fs.readFileSync(path.resolve('../data/test-environment.json'), 'utf8')).admin_password
test('dictionary groups → catalog CRUD → publish same-name image group → auto grouping → delete propagation', async ({ page }) => {
  test.setTimeout(120000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('用户名', { exact: true }).fill('admin')
  await page.getByLabel('密码', { exact: true }).fill(password)
  await page.getByRole('button', { name: '进入工作空间' }).click()
  await page.getByRole('button', { name: 'Tag 翻译', exact: true }).click()
  await page.getByRole('button', { name: '同步为标签', exact: true }).click()
  await expect(page.getByText(/已合并 .* 个分组，新增/)).toBeVisible()
  await page.getByRole('button', { name: '标签探索', exact: true }).click()
  await page.getByLabel('搜索全局分组').fill('人物-头发')
  await page.getByRole('navigation', { name: '全局分组列表' }).getByRole('button', { name: /人物-头发/ }).click()
  await page.getByLabel('搜索组内 Tag').fill('white hair')
  await expect(page.locator('.global-member').first()).toContainText('white hair')
  await page.screenshot({ path: '../test-artifacts/v04-explorer.png', fullPage: true })
  await page.getByLabel('搜索全局分组').fill('')
  const name = `全局验证 ${Date.now()}`
  await page.getByRole('button', { name: '新建全局组', exact: true }).click()
  await page.getByLabel('全局组名称', { exact: true }).fill(name)
  await page.getByRole('dialog').getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: '添加 Tag', exact: true }).click()
  await page.getByLabel('全局英文 Tag').fill('gmv extra')
  await page.getByRole('dialog').getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.locator('.global-member')).toContainText('gmv extra')

  await page.getByRole('button', { name: '导入文件', exact: true }).click()
  await page.getByLabel('选择上传文件', { exact: true }).setInputFiles([
    path.resolve('../backend/tests/fixtures/translations.png'), path.resolve('../backend/tests/fixtures/global-groups.png')])
  await page.getByRole('button', { name: '提交导入' }).click()
  await expect(page.getByRole('status')).toContainText('导入任务已提交')
  await page.getByRole('button', { name: /全部资产/ }).click()
  await expect(page.getByRole('button', { name: '查看 global-groups.png', exact: true })).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: '查看 translations.png', exact: true }).click()
  await page.getByRole('button', { name: '标签', exact: true }).click()
  await page.locator('.token-picker').getByRole('button', { name: 'gmv translation demo', exact: true }).click()
  await page.locator('.token-picker').getByRole('button', { name: 'unknown demo phrase', exact: true }).click()
  await page.getByRole('button', { name: /新建分组/ }).click()
  await page.getByLabel('分组名称', { exact: true }).filter({ visible: true }).last().fill(name)
  const group = page.locator(`.prompt-group:has(input[value="${name}"])`)
  await group.getByRole('button', { name: '全局分组', exact: true }).click()
  await expect(group.getByRole('button', { name: '已全局分组', exact: true })).toBeVisible()
  await page.screenshot({ path: '../test-artifacts/v04-image-group.png', fullPage: true })
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '查看 global-groups.png', exact: true }).click()
  await page.getByRole('button', { name: '标签', exact: true }).click()
  await expect(group).toContainText('unknown demo phrase')
  await expect(group).toContainText('gmv translation demo')
  await group.getByRole('button', { name: '移出 gmv translation demo', exact: true }).click()
  await page.getByRole('button', { name: '保存分组', exact: true }).click()
  await expect(page.getByRole('button', { name: '保存分组', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '标签探索', exact: true }).click()
  await page.getByLabel('搜索全局分组').fill(name)
  await page.getByRole('navigation', { name: '全局分组列表' }).getByRole('button', { name: new RegExp(name) }).click()
  await expect(page.locator('.global-member')).toHaveCount(2)
  await expect(page.locator('.global-group-detail')).toContainText('gmv extra')
  await expect(page.locator('.global-group-detail')).not.toContainText('gmv translation demo')
  await page.getByRole('button', { name: '编辑全局 Tag unknown demo phrase', exact: true }).click()
  await page.getByLabel('全局英文 Tag').fill('blue eyes')
  await page.getByRole('dialog').getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: /全部资产/ }).click()
  await page.getByRole('button', { name: '查看 global-groups.png', exact: true }).click()
  await page.getByRole('button', { name: '标签', exact: true }).click()
  await expect(group).toContainText('blue eyes')
  await expect(group).not.toContainText('unknown demo phrase')
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '标签探索', exact: true }).click()
  await page.getByLabel('搜索全局分组').fill(name)
  await page.getByRole('navigation', { name: '全局分组列表' }).getByRole('button', { name: new RegExp(name) }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '删除全局 Tag blue eyes', exact: true }).click()
  await expect(page.getByRole('button', { name: '删除全局 Tag blue eyes', exact: true })).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.screenshot({ path: '../test-artifacts/v04-mobile.png', fullPage: true })
  expect(errors).toEqual([])
})
